### ISSUE TITLE
User Passwords are stored in plaintext in the database

### ISSUE THREAD

**Issue by hopeseekr** [ketrolac1/php-loginapp#1]
You need to hash them.

**Comment by ketrolac1** [comment]
It is hashed at https://github.com/ketrolac1/php-loginapp/blob/75f4f6b0742a11c08969b51fdbb184d502529613/user/signup_process.php#L36
`    $hashedPwd = password_hash($pwd, PASSWORD_DEFAULT);
                $user->pwd = $hashedPwd;
                //create user
                $user->createUser();`

![Screenshot from 2022-10-15 11-54-33](https://user-images.githubusercontent.com/114992626/195972645-d5cebb54-4dfe-402e-8e09-9df0e52bf5e9.png)
